### ISSUE TITLE
Notify in telegram version 0.4.0  

### ISSUE THREAD

**Issue by anphn** [metalmatze/alertmanager-bot#63]
Hi metalmatze, im use version 0.3.0 my notify very ok but when i update version 0.4.0 my notify dont have any information. 
![DeepinScreenshot_select-area_20190510140732](https://user-images.githubusercontent.com/50355074/57508880-f5bbed80-732c-11e9-91a5-d7972014f657.png)

**Comment by lazysmokier** [comment]
Default template has changed in this version. Now it uses 'message' annotation instead of 'summary' and 'description' annotations as it was earlier (please see https://github.com/metalmatze/alertmanager-bot/blob/master/default.tmpl to figure out how template would render)

So the general advice - just replace 'summary' annotation key in your prometheus alerting rules with 'message'. Alternatively you may override default.tmpl with your own and use 'summary' and 'description' annotations in it

**Comment by metalmatze** [comment]
Yes, that's correct. I adopted the changes we did in kube-prometheus a while ago.
